version: "3.7"

services:
  api_service:
    build: .
    container_name: spring-boot-mysql-base-project_api_service
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      app_db:
        condition: service_healthy
    environment:
     SPRING_DATASOURCE_URL: jdbc:mysql://app_db:3306/java_to_dev_app_db
  app_db:
    container_name: app_db
    image: mysql:oracle
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: java_to_dev_app_db
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 2s
      retries: 30